version: '2'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-use-native-aio=0

    volumes:
      - /mnt/ssd/nextcloud-db:/var/lib/mysql  # Mount MariaDB data to /mnt/ssd/nextcloud/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=z8OPOx1CR7rLl3Zk7c71rp8IE
      - MYSQL_PASSWORD=vi5A6fjxmqwgwSh
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8888:80
    volumes:
      - /mnt/ssd/nextcloud:/var/www/html  # Mount Nextcloud data to /mnt/ssd/nextcloud
    environment:
      - MYSQL_PASSWORD=vi5A6fjxmqwgwSh
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
 